module.exports = {
  enums: [],
  models: [
    {
      name: 'RW_DataMigration',
      dbName: null,
      fields: [
        {
          name: 'version',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'startedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'DateTime',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'finishedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'DateTime',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
    },
    {
      name: 'Job',
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          isReadOnly: false,
          type: 'Int',
          hasDefaultValue: true,
          default: {
            name: 'autoincrement',
            args: [],
          },
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'DateTime',
          hasDefaultValue: true,
          default: {
            name: 'now',
            args: [],
          },
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'title',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'description',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'price',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'Int',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'longitude',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'latitude',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'threeWords',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'status',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'timeout',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'DateTime',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'additionalAddressInformation',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'categories',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'JobCategoriesOnJob',
          hasDefaultValue: false,
          relationName: 'JobToJobCategoriesOnJob',
          relationFromFields: [],
          relationToFields: [],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
    },
    {
      name: 'JobUser',
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          isReadOnly: false,
          type: 'Int',
          hasDefaultValue: true,
          default: {
            name: 'autoincrement',
            args: [],
          },
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'jobId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'Int',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'userId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
    },
    {
      name: 'JobCategory',
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          isReadOnly: false,
          type: 'Int',
          hasDefaultValue: true,
          default: {
            name: 'autoincrement',
            args: [],
          },
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'type',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'String',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'jobs',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'JobCategoriesOnJob',
          hasDefaultValue: false,
          relationName: 'JobCategoriesOnJobToJobCategory',
          relationFromFields: [],
          relationToFields: [],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
    },
    {
      name: 'JobCategoriesOnJob',
      dbName: null,
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: true,
          isReadOnly: false,
          type: 'Int',
          hasDefaultValue: true,
          default: {
            name: 'autoincrement',
            args: [],
          },
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'job',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'Job',
          hasDefaultValue: false,
          relationName: 'JobToJobCategoriesOnJob',
          relationFromFields: ['jobId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'jobId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: true,
          type: 'Int',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'category',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'JobCategory',
          hasDefaultValue: false,
          relationName: 'JobCategoriesOnJobToJobCategory',
          relationFromFields: ['categoryId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'categoryId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: true,
          type: 'Int',
          hasDefaultValue: false,
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'assigendAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          type: 'DateTime',
          hasDefaultValue: true,
          default: {
            name: 'now',
            args: [],
          },
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      isGenerated: false,
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
    },
  ],
  types: [],
};
