// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db';
import datamodel from 'src/models/datamodel';
import { RedwoodRecord } from '@redwoodjs/record';

RedwoodRecord.db = db;
RedwoodRecord.schema = datamodel;

import Job from 'src/models/Job';
import JobCategory from 'src/models/JobCategory';
import JobUser from 'src/models/JobUser';

Job.requiredModels = [];
JobCategory.requiredModels = [];
JobUser.requiredModels = [];

export { Job, JobCategory, JobUser };
