name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: steve-jobs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.14.0'

      - name: 💿 Cache
        id: cache-dep
        uses: actions/cache@v2
        with:
          path: |
            dm-jobs/node_modules
            */*/node_modules
          key: ${{ runner.dm-jobs }}-steve-jobs-${{ hashFiles('**/package.json') }}

      - name: init
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: |
          cd dm-jobs
          export NODE_OPTIONS="--max-old-space-size=6144"
          yarn install

      - name: test backend
        run: |
          cd dm-jobs
          yarn rw test api --no-watch --ci --outputFile=test_result.json --json

      - name: test frontend
        run: |
          cd dm-jobs
          yarn rw test web --no-watch --ci --outputFile=test_result.json --json

      - name: lint
        if: always()
        run: |
          cd dm-jobs
          yarn rw lint
